### ISSUE TITLE
Loading Screen when switching Mensa

### ISSUE THREAD

**Issue by lilioid** [fredericobormann/MensaViewer#7]
When you switch between different Mensas the old data gets displayed as long as the new data is not loaded.

It would be nice to have some sort of loading screen. For example an empty page with a loading circle in the middle.
An elternative would be to preload all three Mensas at once and display it instantly.

**Comment by fredericobormann** [comment]
Preloading and caching data will be implemented in future releases, but this will require some bigger changes. So I chose to just hide the old data when a new Mensa is selected – for now.
